title: "Matthew Freeman"
description: "My personal website"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/

excerpt_separator: <!--more-->

show_excerpts: true

author:
  name: "Matthew Freeman"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "My personal website for displaying my skills"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/matthew-damon-freeman"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:matthewfreeman12345@yahoo.com"
