title: "Matthew Freeman"
description: "My personal website"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

header:
  nav: main

collections:
  projectsgis:
    output: true
    permalink: /projectsgis/:name/
  projectsarduino:
    output: true
    permalink: /projectsarduino/:name/

excerpt_separator: <!--more-->

author:
  name: "Matthew Freeman"
  avatar: "/images/bio-photo.jpg"
  bio: "My personal website for displaying my skills"

  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/matthew-damon-freeman"

    - label: "Email"
      icon: "fas fa-envelope"
      url: "matthewfreeman12345@yahoo.com"
